config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users

  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/contact'
  get 'welcome/faq'
  get 'welcome/pricing'
  get 'welcome/features'

  resources :companies do
    collection { post :import }
  end

  resources :invoices do
    resources :purchases, except: [:index, :show]
  end

  resources :employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Company.create! row.to_hash
    end
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      
      all.each do |company|
        csv << company.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :invoices
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :employee
  has_many :purchases, dependent: :destroy
end

app/models/invoice_search.rb
class InvoiceSearch
  attr_reader :date_from, :date_to

  def initialize(params)
    params ||= {}
    @date_from = parsed_date(params[:date_from], 1.year.ago.to_date.to_s)
    @date_to   = parsed_date(params[:date_to], Date.today.end_of_month.to_s)
  end

  def scope
    Invoice.where('date BETWEEN ? AND ?', @date_from, @date_to)
  end

  private
    def parsed_date(date_string, default)
      Date.parse(date_string)
    rescue ArgumentError, TypeError
      default
    end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :invoice
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  def index
    @companies = Company.all

    respond_to do |format|
      format.html
      format.csv { send_data @companies.to_csv,
        filename: "companies-#{Date.today}.csv"}
    end
  end

  def show
  end

  def new
    @company = Company.new
  end

  def edit
  end

  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to @company, notice: 'Company was successfully created.'
    else
      render :new
    end
  end

  def update
    if @company.update(company_params)
      redirect_to @company, notice: 'Company was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @company.destroy
    redirect_to companies_url, notice: 'Company was successfully destroyed.'
  end

  def import
    Company.import(params[:file])
    redirect_to companies_path, notice: 'Companies imported successfully'
  end

  private
    def set_company
      @company = Company.find(params[:id])
    end

    def company_params
      params.require(:company).permit(:name, :manager, :status, :terms)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  def index
    @employees = Employee.all
  end

  def show
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to @employee, notice: 'Employee was successfully created.'
    else
      render :new
    end
  end

  def update
    if @employee.update(employee_params)
      redirect_to @employee, notice: 'Employee was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @employee.destroy
    redirect_to employees_path, notice: 'Employee was successfully destroyed.'
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:name, :phone, :job_type)
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  def index
    @search = InvoiceSearch.new(params[:search])
    @invoices = @search.scope
  end

  def show
    @purchases = @invoice.purchases
  end

  def new
    @invoice = Invoice.new
  end

  def edit
  end

  def create
    @invoice = Invoice.new(invoice_params)

    if @invoice.save!
      redirect_to @invoice, notice: 'Invoice was successfully created.'
    else
      render :new, notice: @invoice.errors
    end
  end

  def update
    if @invoice.update(invoice_params)
      redirect_to @invoice, notice: 'Invoice was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @invoice.destroy
    redirect_to invoices_url, notice: 'Invoice was successfully destroyed.'
  end

  private
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    def invoice_params
      params.require(:invoice).permit(:date, :company, :tax, :employee_id, :status_type)
    end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_invoice
  before_action :set_purchase, except: [:new, :create]

  def new
    @purchase = Purchase.new
  end

  def edit
    @purchase = Purchase.find(params[:id])
  end

  def create
    @purchase = @invoice.purchases.new(purchase_params)

    if @purchase.save
      redirect_to @invoice, notice: 'Purchase was successfully created.'
    else
      render :new
    end
  end

  def update
    if @purchase.update(purchase_params)
      redirect_to @invoice, notice: 'Purchase was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @purchase = Purchase.find(params[:id])

    if @purchase.destroy
      flash[:notice] = "'#{@purchase.name}' was deleted successfully"
      redirect_to @invoice
    else
      flash[:error] = 'There was an error deleting the purchase'
      render :show
    end
  end

  private
    def set_invoice
      @invoice = Invoice.find(params[:invoice_id])
    end

    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    def purchase_params
      params.require(:purchase).permit(:name, :category, :quantity,
                                       :invoice_id, :price)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def faq
  end

  def pricing
  end

  def features
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
  def line_item_total(purchase)
    purchase.quantity * purchase.price
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :manager %>
    <%= form.text_field :manager %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :terms %>
    <%= form.number_field :terms %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Companies</h1>

<div class="media">
  <div class="media-body">
    <table class='table table-hover'>
      <thead>
        <tr>
          <th>Name</th>
          <th>Manager</th>
          <th>Status</th>
          <th>Terms</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @companies.each do |company| %>
          <tr>
            <td><%= link_to company.name, company %></td>
            <td><%= company.manager %></td>
            <td><%= company.status %></td>
            <td><%= company.terms %></td>
            <td><%= link_to 'Edit', edit_company_path(company), class: 'btn btn-xs btn-success' %></td>
            <td><%= link_to 'Destroy', company, method: :delete, class: 'btn btn-xs btn-danger', data: { confirm: "Are you sure you want to delete '#{company.name}'?" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<h3>Import Companies</h3>
<%= form_tag import_companies_path, multipart: true do %>
  <%= file_field_tag :file %>

  <%= submit_tag 'Upload Companies', class: 'btn btn-default' %>
<% end %>

<h3>Download File</h3>
<%= link_to 'Report', companies_path(format: 'csv'), class: 'btn btn-default' %>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Manager:</strong>
  <%= @company.manager %>
</p>

<p>
  <strong>Status:</strong>
  <%= @company.status %>
</p>

<p>
  <strong>Terms:</strong>
  <%= @company.terms %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :job_type %>
    <%= form.text_field :job_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Employees</h1>

<div class="media">
  <div class="media-body">
    <table class='table table-hover'>
      <thead>
        <tr>
          <th>Name</th>
          <th>Phone</th>
          <th>Job type</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @employees.each do |employee| %>
          <tr>
            <td><%= link_to employee.name, employee %></td>
            <td><%= employee.phone %></td>
            <td><%= employee.job_type %></td>
            <td><%= link_to 'Edit', edit_employee_path(employee), class: 'btn btn-xs btn-default' %></td>
            <td><%= link_to 'Destroy', employee, method: :delete, class: 'btn btn-xs btn-danger', data: { confirm: "Are you sure you want to delete '#{employee.name}'?" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employee.phone %>
</p>

<p>
  <strong>Job type:</strong>
  <%= @employee.job_type %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/invoices/_form.html.erb
<%= form_with model: invoice, class: 'form-horizontal' do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.date_select :date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :company %>
    <%= form.text_field :company, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :tax %>
    <%= form.text_field :tax, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :employee_id %>
    <div class="controls">
      <%= collection_select(:invoice, :employee_id, Employee.order(name: :asc), :id, :name, {}, { multiple: false }) %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label 'Status' %>
    <div class="controls">
      <%= form.select(:status_type, options_for_select([['PAID', 'PAID'], ['PENDING', 'PENDING']], 'PENDING')) %>
    </div>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1>Edit Invoice</h1>

    <%= render 'form', invoice: @invoice %>

    <%= link_to 'Show', @invoice %> |
    <%= link_to 'Back', invoices_path %>
  </div>
</div>

app/views/invoices/index.html.erb
<div class="row">
  <h1>Invoices</h1>
  <div class="pull-right range-query">
    <%= form_tag invoices_path, method: :get do %>
      <%= text_field_tag 'search[date_from]', @search.date_from %>
      <%= text_field_tag 'search[date_to]', @search.date_to %>
      <%= submit_tag 'Search', class: 'btn search-button' %>
    <% end %>
  </div>
</div>

<div class="media">
  <div class="media-body">
    <table class='table table-hover'>
      <thead>
        <tr>
          <th>Date</th>
          <th>Company</th>
          <th>Tax</th>
          <th>Salesperson</th>
          <th>Status</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @invoices.each do |invoice| %>
          <tr>
            <td><%= invoice.date.strftime("%Y-%m-%d") %></td>
            <td><%= link_to invoice.company, invoice_path(invoice) %></td>
            <td><%= invoice.tax %></td>
            <td><%= invoice.employee.name %></td>
            <td><%= invoice.status_type %></td>
            <td><%= link_to 'Edit', edit_invoice_path(invoice), class: 'btn btn-xs btn-success' %></td>
            <td><%= link_to 'Destroy', invoice, method: :delete, class: 'btn btn-xs btn-danger', data: { confirm: "Do you want to delete '#{invoice.company}'?" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<div class="invoice-info">
  <p>
    <strong>Date:</strong>
    <%= @invoice.date.strftime("%Y-%m-%d") %>
  </p>

  <p>
    <strong>Company:</strong>
    <%= @invoice.company %>
  </p>

  <p>
    <strong>Tax:</strong>
    <%= @invoice.tax %>
  </p>

  <p>
    <strong>Salesperson:</strong>
    <%= @invoice.employee.name %>
  </p>
</div>

<br>

<% if @purchases.any? %>
  <div class="media">
    <div class="media-body">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Category</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total</th>
            <th colspan='2'></th>
          </tr>
        </thead>
        <tbody>
          <% running_total = 0 %>
          <% @purchases.each do |purchase| %>
            <tr>
              <td><h4><%= purchase.name %></h4></td>
              <td><h4><%= purchase.category %></h4></td>
              <td><h4><%= purchase.quantity %></h4></td>
              <td><h4><%= number_to_currency(purchase.price) %></h4></td>
              <td><h4><%= number_to_currency(line_item_total(purchase)) %></h4></td>
              <td><h4><%= link_to 'Edit', edit_invoice_purchase_path(@invoice, purchase), class: 'btn btn-xs btn-success' %></h4></td>
              <td>
                <h4>
                  <%= link_to 'Delete', [@invoice, purchase],
                      class: 'btn btn-xs btn-danger',
                      method: :delete,
                      data: { confirm: "Are you sure you want to delete '#{purchase.name}' from this invoice?" } %>
                </h4>
              </td>
              <% running_total += purchase.quantity * purchase.price %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

<h2 class="pull-right">
  Invoice Total: <%= number_to_currency(running_total) %>
</h2>

<br><br><br><br>

<%= link_to 'Add New Item', new_invoice_purchase_path(@invoice), class: 'pull-right' %>

<br>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

app/views/layouts/_alerts.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class='close' data-dismiss='alert'>
      &times;
    </button>
    <%= flash[:notice] %>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-error">
    <button type="button" class='close' data-dismiss='alert'>
      &times;
    </button>
    <%= flash[:error] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-warning">
    <button type="button" class='close' data-dismiss='alert'>
      &times;
    </button>
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<ul class="nav nav-tabs">
  <li><%= link_to 'Home', root_path %>
  <li><%= link_to 'About Us', welcome_about_path %></li>
  <li><%= link_to 'Contact', welcome_contact_path %></li>
  <li><%= link_to 'Features', welcome_features_path %></li>
  <li><%= link_to 'FAQs', welcome_faq_path %></li>
  <li><%= link_to 'Pricing', welcome_pricing_path %></li>

  <% if current_user %>
    <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
    <div class="btn-group pull-right right-nav">
      <button type="button"
              class='btn btn-xs dropdown-toggle'
              data-toggle='dropdown'>
        <span class="caret"></span>
        <span class="sr-only">Admin</span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to 'Invoices', invoices_path %></li>
        <li><%= link_to 'Employees', employees_path %></li>
        <li><%= link_to 'Companies', companies_path %></li>
      </ul>
    </div>
  <% else %>
    <li><%= link_to 'Sign Up', new_user_registration_path %></li>
    <li><%= link_to 'Sign In', new_user_session_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invoices</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/nav' %>
      <%= render 'layouts/alerts' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/purchases/_form.html.erb
<%= form_with(model: [@invoice, purchase], local: true) do |form| %>
  <% if purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% purchase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :category %>
    <%= form.text_field :category, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/purchases/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1>Edit Purchase</h1>

    <%= render 'form', purchase: @purchase %>
  </div>
</div>

app/views/purchases/new.html.erb
<h1>New Purchase</h1>

<%= render 'form', purchase: @purchase %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me anywhere</p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/faq.html.erb
<h1>Welcome#faq</h1>
<p>Find me in app/views/welcome/faq.html.erb</p>

app/views/welcome/features.html.erb
<h1>Welcome#features</h1>
<p>Find me in app/views/welcome/features.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/pricing.html.erb
<h1>Welcome#pricing</h1>
<p>Find me in app/views/welcome/pricing.html.erb</p>